import Card from "../components/Home/Card";
import Footer from "../components/Home/Footer";
import Header from "../components/Home/Header";
import Introduction from "../components/Home/Introduction";
import SliderHomePage from "../components/Home/SliderHomePage";
import { useEffect, useState } from "react";
import { Router, useRouter } from "next/router";
import { useDispatch } from "react-redux";
import { setHomePageData } from "../app/homePageSlice";
import { getData } from "../app/api/home";
import Head from "next/head";
import ReactLoading from "react-loading";
import Country from "../components/Home/Country";

const items = [
  { distance: "28 MPH (45 KPH)", detatails: "MAX SPEED", id: 1 },
  {
    distance: "75 MILES (120 KM)",
    detatails: "MAX RANGE",
    id: 2,
    borderRL: true,
  },
  { distance: "250 to 500 w/120 NM", detatails: "MAX POWER/TORQUE", id: 3 },
];

function HomePage({ homePageData, countries, products }) {
  const router = useRouter();
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setHomePageData(homePageData));
  }, [router]);

  const [loading, setLoading] = useState(false);

  return (
    <div>
      <Head>
        <meta
          name="description"
          content="The most affordable carbon fiber smart e-bike."
        />
        <meta
          name="keywords"
          content="Nireeka, ebike, carbon fiber, affordable, "
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:image"
          content="https://nireeka.com/images/promo/nyx-promo-1.jpg"
        />
        <meta property="og:url" content="https://nireeka.com" />
        <meta property="og:site_name" content="Nireeka Bikes" />
        <meta property="og:title" content="Carbon-Fiber Smart E-Bikes" />

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://nireeka.com/images/logo_wfJ_icon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;600&display=swap"
          rel="stylesheet"
        />

        <title>Nireeka Bikes | Carbon-Fiber Smart E-Bikes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {loading ? (
        <>
          <div className="w-full h-screen mx-auto my-auto ">
            <ReactLoading
              type="spin"
              color="rgb(209, 213, 219)"
              height={80}
              width={80}
              className="h-screen mx-auto py-200"
            />
          </div>
        </>
      ) : (
        <>
          <section>
            <div className="relative ">
              <div className="w-full">
                <Header />
              </div>
              <div className="flex items-center object-cover w-full h-screen bg-center bg-no-repeat bg-cover lg:bg-banner-homepage-lg bg-banner-homepage-lg">
                <div className="self-end hidden w-full md:flex">
                  <div className="relative flex min-w-0 mx-auto mb-8 break-words bg-transparent w-750 glass text-gray-50 ">
                    {items.map((item) => (
                      <div
                        className={` font-light text-center flex-auto px-4 py-5 ${
                          item.borderRL
                            ? "border-x border-nireekaBorderColor"
                            : ""
                        } `}
                        key={item.id}
                      >
                        <h6 className="text-xl font-light ">{item.distance}</h6>
                        <p className="mt-2 mb-4 font-light text-gray-300 ">
                          {item.detatails}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section></section>
          <section className="mt-5 md:mt-20">
            <Introduction />
            <Card />
          </section>
          <Country countries={countries} products={products} />
          <SliderHomePage />
          <Footer />
        </>
      )}
    </div>
  );
}

export default HomePage;

export const getStaticProps = async () => {
  let data = await getData();
  const res = await fetch(`http://nireeka.com/api/countries`);
  const countries = await res.json();
  const resProduct = await fetch(`https://nireeka.com/api/bikes/list`);
  const products = await resProduct.json();

  return {
    props: { homePageData: data, countries, products },
  };
};
